vaxspace/vaxapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'vaxapp'

urlpatterns = [
    path('', views.login, name='login'),
    path('user_register/', views.user_register, name='user_register'),
    path('index/', views.index, name='index'),
    path('index/utilities/', views.utilities, name='utilities'),
    path('index/healthworker/', views.healthworker, name='healthworker'),
    path('index/barangay/', views.barangay, name='barangay'),
    path('index/guardian/', views.guardian, name='guardian'),
    path('add_healthworker/', views.add_healthworker, name='add_healthworker'),
    path('charts/', views.charts, name='charts'),
    path('tables/', views.tables, name='tables'),
    path('admin_tables/', views.admin_tables, name='admin_tables'),
    path('buttons/', views.buttons, name='buttons'),
    path('admin_tables/add_record/<int:id>/', views.add_record, name='admin_add_record'),
    path('tables/add_record/<int:id>/', views.add_record, name='add_record'), 
    path('tables/confirmation/<int:id>/', views.confirmation, name='confirmation'),
    path('logout/', views.logout, name='logout'),
]

vaxspace/vaxspace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vaxapp.urls', namespace="vaxapp")),
]

vaxspace/vaxapp/models.py
from django.db import models
from operator import mod
from django.utils import timezone
from unittest.util import _MAX_LENGTH
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Barangay(models.Model):
    name = models.CharField(max_length = 100)
    healthworker = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name



class Vaccine(models.Model):
    name = models.CharField(max_length = 100)
    description = models.CharField(max_length = 100)
    dose1 = models.BooleanField(null=True)
    dose2 = models.BooleanField(null=True)
    dose3 = models.BooleanField(null=True)
    created = models.DateTimeField(default=timezone.now)
    recommended_age1 = models.CharField(max_length=50, null=True) 
    recommended_age2 = models.CharField(max_length=50, null=True) 
    recommended_age3 = models.CharField(max_length=50, null=True) 

    def __str__(self):
        return self.name

class Register(models.Model):

    child_name = models.CharField(max_length = 100,null=True)       
    date_of_birth = models.DateField(null=True)     
    place_of_birth = models.CharField(max_length = 100,null=True)  
    address = models.ForeignKey(Barangay, null=True, on_delete=models.CASCADE) 
    contact = models.IntegerField(null=True)  
    mother_name = models.CharField(max_length = 100,null=True)       
    father_name = models.CharField(max_length = 100 , null=True)   
    birth_height = models.IntegerField(null=True) 
    birth_weight = models.IntegerField(null=True) 
    sex = models.CharField(max_length = 10, null=True)
    added_by = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    
    

    def __str__(self):
        return self.child_name

class Vaccine_record(models.Model):
    child = models.ForeignKey(Register, default=None, on_delete=models.CASCADE)
    vaccine_info = models.TextField(default=None)


class Disease(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=100)
    vaccine = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Schedule(models.Model):
    child = models.ForeignKey(Register, on_delete=models.SET_NULL, null=True)       
    vax_date = models.DateTimeField(null=True)
    brgy = models.ForeignKey(Barangay, on_delete=models.SET_NULL, null=True)
    guardian = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    vaccine_info = models.TextField(default=None)
    def __str__(self):
        return self.child

vaxspace/vaxapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Register, Vaccine
from django import forms





class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email', 'password1', 'password2']
         

vaxspace/vaxapp/views.py
from django.shortcuts import render, redirect
from contextlib import redirect_stderr
from http.client import HTTPResponse
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from vaxapp import views
from django.contrib.auth.models import Group
from datetime import datetime, date, timedelta, time
from django.utils.timezone import localdate
from django.utils import timezone
import pytz
from .forms import CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.

def login(request):
    if request.method == 'POST' :
        username = request.POST[ 'username' ]
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        
        if user is not None:
            auth.login(request, user)
            return redirect("index/")
        else:
            messages.error(request, 'Invalid credentials.')
            return redirect( '/')

    return render(request, 'vaxapp/login.html')

@allowed_users(allowed_roles=['admin', 'healthworker'])
@admin_only
def index(request):
    vaccine = Vaccine.objects.all()
    vax_count = vaccine.count()
    regs = Register.objects.all()
    regs_count = regs.count()
    disease = Disease.objects.all()
    disease_count = disease.count()
    guardian = User.objects.filter(groups=3)
    user_count = guardian.count()
    healthworker = User.objects.filter(groups=2)
    worker_count = healthworker.count()
    barangay = Barangay.objects.all()
    bar_count = barangay.count()
    
    context = {
        'vax_count':vax_count,
        'vaccine':vaccine,
        'regs': regs,
        'regs_count': regs_count,
        'disease':disease,
        'disease_count':disease_count,
        'user_count': user_count,
        'worker_count': worker_count,
        'bar_count': bar_count,
        'brgy': barangay,
    }
    if request.method == 'POST':
        
                child_name = request.POST.get('child_name')
                date_of_birth = request.POST.get('date_of_birth')
                place_of_birth = request.POST.get('place_of_birth')
                address = request.POST.get('address')
                contact = request.POST.get('contact')
                mother_name = request.POST.get('mother_name')
                father_name = request.POST.get('father_name')
                birth_height = request.POST.get('birth_height')
                birth_weight = request.POST.get('birth_weight')
                sex = request.POST.get('sex')
                added_by = request.user

                if Register.objects.filter(child_name = child_name).exists():
                    messages.error(request, 'Already registered.')
                    return redirect('index/..')
                else:
                    address_instance = Barangay.objects.get(name=address)
                    registered = Register(child_name=child_name,date_of_birth=date_of_birth, place_of_birth=place_of_birth, mother_name=mother_name,father_name=father_name,address=address_instance,contact=contact,birth_height=birth_height, birth_weight=birth_weight, sex=sex, added_by=added_by)
                    registered.save()
                    messages.success(request, "Registered successfully.")
                    return redirect('index/..')

    return render(request, 'vaxapp/index.html', context)


@allowed_users(allowed_roles=['healthworker'])
def healthworker(request):
    assign = Barangay.objects.get(healthworker=request.user)
    records = Register.objects.filter(address=assign)
    vax_sched = Schedule.objects.filter(brgy=assign)
    vaccine = Vaccine.objects.all()
    vax_count = vaccine.count()
    records_count = records.count()
    disease = Disease.objects.all()
    disease_count = disease.count()
    guardian = User.objects.filter(groups=3)
    user_count = guardian.count()
    sched_count = vax_sched.count()
    brgy = Barangay.objects.all()
    context = {
        'assign': assign,
        'records': records,
        'vax_sched': vax_sched,
        'vax_count':vax_count,
        'vaccine':vaccine,
        'records_count': records_count,
        'disease':disease,
        'disease_count':disease_count,
        'user_count': user_count,
        'sched_count': sched_count,
        'brgy':brgy
    }
    if request.method == 'POST':
        
                child_name = request.POST.get('child_name')
                date_of_birth = request.POST.get('date_of_birth')
                place_of_birth = request.POST.get('place_of_birth')
                address = request.POST.get('address')
                contact = request.POST.get('contact')
                mother_name = request.POST.get('mother_name')
                father_name = request.POST.get('father_name')
                birth_height = request.POST.get('birth_height')
                birth_weight = request.POST.get('birth_weight')
                sex = request.POST.get('sex')
                added_by = request.user

                if Register.objects.filter(child_name = child_name).exists():
                    messages.error(request, 'Already registered.')
                    return redirect('index/healthworker/..')
                else:
                    address_instance = Barangay.objects.get(name=address)
                    registered = Register(child_name=child_name,date_of_birth=date_of_birth, place_of_birth=place_of_birth, mother_name=mother_name,father_name=father_name,address=address_instance,contact=contact,birth_height=birth_height, birth_weight=birth_weight, sex=sex, added_by=added_by)
                    registered.save()
                    messages.success(request, "Registered successfully.")
                    return redirect('index/healthworker/..')

    return render(request, 'vaxapp/healthworker.html', context)

def add_healthworker(request):
    form = CreateUserForm()
    brgy = Barangay.objects.all()
    context = {
        'form':form,
        'brgy':brgy
        }

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        
        if form.is_valid():

            user = form.save()
            
            group = Group.objects.get(name='healthworker')
            user.groups.add(group)
            messages.success(request, "Account created successfully.")
            return redirect('index/..')
        else:
            messages.error(request, "Already created.")
            redirect ('add_healthworker/..')
    
    
    return render(request, 'vaxapp/add_healthworker.html', context)

def user_register(request):
    form = CreateUserForm()
    brgy = Barangay.objects.all()
    context = {
        'form':form,
        'brgy':brgy
        }

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        
        if form.is_valid():

            user = form.save()
            
            group = Group.objects.get(name='guardian')
            user.groups.add(group)
            messages.success(request, "Account created successfully.")
            return redirect('/')
        else:
            messages.error(request, "Already created.")
            redirect ('user_register/..')
    
    
    return render(request, 'vaxapp/register.html', context)

@login_required(login_url='/')
def guardian(request):
        brgy = Barangay.objects.all()
        profile = request.user
        children = Register.objects.filter(added_by=profile)
        children_count = children.count()
        specific_group = Group.objects.filter(user=profile, name='guardian').first()
        try:
            child_sched = Schedule.objects.filter(guardian=profile)
            child_count = child_sched.count()

        except Schedule.DoesNotExist:
            child_sched = None

           
        context = {
            'brgy':brgy,
            'profile':profile,
            'children':children,
            'children_count':children_count,
            'specific_group':specific_group,
            'child_sched':child_sched,
            'child_count': child_count
        }
        if request.method == 'POST':
        
                child_name = request.POST.get('child_name')
                date_of_birth = request.POST.get('date_of_birth')
                place_of_birth = request.POST.get('place_of_birth')
                address = request.POST.get('address')
                contact = request.POST.get('contact')
                mother_name = request.POST.get('mother_name')
                father_name = request.POST.get('father_name')
                birth_height = request.POST.get('birth_height')
                birth_weight = request.POST.get('birth_weight')
                sex = request.POST.get('sex')
                added_by = request.user

                if Register.objects.filter(child_name = child_name).exists():
                    messages.error(request, 'Already registered.')
                    return redirect('guardian/..')
                else:
                    address_instance = Barangay.objects.get(name=address)
                    registered = Register(child_name=child_name,date_of_birth=date_of_birth, place_of_birth=place_of_birth, mother_name=mother_name,father_name=father_name,address=address_instance,contact=contact,birth_height=birth_height, birth_weight=birth_weight, sex=sex, added_by=added_by)
                    registered.save()
                    messages.success(request, "Registered successfully.")
                    return redirect('guardian/..')

        return render(request, 'vaxapp/guardian.html', context)



def barangay(request):
    assign_brgy = User.objects.filter(groups=2)
    brgy_data = Barangay.objects.all()
    context = {
        'assign_brgy': assign_brgy,
        'brgy_data': brgy_data,
    }

vaxspace/vaxapp/templates/vaxapp/add_healthworker.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"><img src="{% static 'img/main.png' %}"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>CREATE AN ACCOUNT FOR HEALTHWORKER</strong></h1>
                            </div>
                            <form method="POST" class="user" style="text-align:center;color:black">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{form.first_name.label}} {{form.first_name}}
                                    </div>
                                    <div class="col-sm-6">
                                        {{form.last_name.label}} {{form.last_name}}
                                    </div>
                                </div>
                             
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{form.username.label}} {{form.username}}
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        {{form.email.label}} {{form.email}}
                                    </div>
                                    <div class="col-sm-6">
                                        {{form.password1.label}} {{form.password1}}
                                    </div>
                                    <div class="col-sm-6">
                                        {{form.password2.label}} {{form.password2}}
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-warning btn-user btn-block" value="Add account">
                              
                               
                            </form>
                            <hr>
                        
                            <div class="text-center">
                                <a class="small" href="{% url 'vaxapp:index' %}"><button class="btn btn-danger ">GO BACK</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/barangay.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/vaxspace_logo.png' %}">


    <title>VAXSPACE</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"><img style="width:100%" src="{% static 'img/hall.png' %}"></div>
                    <div class="col-lg-7 ">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>ADD NEW BARANGAY</strong></h1>
                            </div>
                            <form method="POST" class="user" style="text-align:center;color:black">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="brgy_name">Barangay name:</label>
                                        <input type="text" id="brgy_name" name="name" placeholder="Add new barangay" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="assign">Select healthworker</label><br>
                                        <select id="assign" name="healthworker">
                                            <option value="{{ user.first_name }}">----------</option>
                                            {% for assign in assign_brgy %}
                                            <option>{{assign.first_name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                           
                                </div>
                               
                                <div class="text-center"> 
                                    <a href="{% url 'vaxapp:index' %}" class="btn btn-danger ">GO BACK</a>
                                    <input type="submit" class="btn btn-warning" value="Add barangay">
                                </div>
                               
                            </form>
                            <hr>
                        
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/confirmation.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VAXSPACE</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"><img style="width:max-content" src="{% static 'img/main.png' %}"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>CONFIRM VACCINATION</strong></h1>
                            </div>
                            <form method="POST" class="user" style="text-align:center;background-color:#eeeeee;opacity:90%;border-radius:5px;padding:10px">
                                {% csrf_token %}
                               
                                    <div style="text-align:center" class="row">
                                        <div class="col">
                                        <input type="hidden"  name="child_id" value="{{confirm.child.id}}" >
                                        <input type="hidden"  name="birthheight" value="{{confirm.child.birth_height}}" >
                                        <input type="hidden"  name="birthweight" value="{{confirm.child.birth_weight}}" >
                                        <input type="hidden"  name="vax_info" value="{{confirm.vaccine_info}}" >
                                        <input type="hidden"  name="vaxdate" value="{{confirm.vax_date}}" >

                                    <h4>{{confirm.child}}<br><sup>Child's Name</sup></h4>
                                    <hr class="sidebar-divider d-none d-md-block">
                                    <h5>{{confirm.vaccine_info}}<br><sup>Vaccines & Doses</sup></h5>
                                    <hr class="sidebar-divider d-none d-md-block">
                                    <h5>{{confirm.vax_date}}<br><sup>Vaccination date</sup></h5>
                                    <hr class="sidebar-divider d-none d-md-block">
                                        <sup>Birth height</sup><input type="text" name="b_height" placeholder="Previous height:{{confirm.child.birth_height}}cm" required>
                                        <sup>Birth weight</sup><input type="text" name="b_weight" placeholder="Previous height:{{confirm.child.birth_weight}}lbs" required>
                                        <hr class="sidebar-divider d-none d-md-block">
                                      
                                    </div>
                                   
                                </div>
                                <br>
                                
                                <a href="{% url 'vaxapp:tables' %}" class="btn btn-danger ">Cancel</a>
                                <input type="submit" class="btn btn-success" value="Save changes">
                                </div>
                               
                                
                               
                            </form>
                            <hr>
                        
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/vaxspace_logo.png' %}">
    <meta name="author" content="">

    <title>VAXSPACE</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">
</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">
        
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0 ">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block"><img src="{% static 'img/vaccine.png' %}"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    
                                    <form method="POST" style="opacity: 95%; padding:5px; border-radius:5px" class="user bg-light">
                                        {% csrf_token %}
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4"><strong>Welcome to VAXSPACE</strong></h1>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputEmail"
                                                placeholder="Enter Username..." name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password" name="password" required>
                                        </div>
                                   
                                        <input type="submit" class="btn btn-primary btn-user btn-block" value="Login">
                           
                                        <hr>
                                        <div class="text-center">
                                        <a class="small" href="{% url 'vaxapp:user_register' %}">Create an Account</a>
                                    </div>
                                    </form>
                                    <hr>
                                        
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    
    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>
</body>

</html>